server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Garante que os ficheiros do TownSquare (.mjs) são lidos corretamente pelo navegador
    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    # Configuração padrão para Single Page Applications (React)
    location / {
        try_files $uri $uri/ /index.html;
    }
}