services:
  db:
    image: postgres:14
    container_name: gamelib-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamelib_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gamelib-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: gamelib-backend
    restart: always
    env_file:
      - ./backend/.env
    # CORREÇÃO: Define explicitamente o anfitrião da base de dados para o Docker
    environment:
      - DB_HOST=db
    ports:
      - "3000:3000"
    networks:
      - gamelib-network
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: gamelib-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - gamelib-network

networks:
  gamelib-network:
    driver: bridge
